### ISSUE TITLE
Schematics for full usb-c port (with alt-DP)

### ISSUE THREAD

**Issue by gehee** [swdee/radxa-cm5-kicad#1]
Can you share the schematics for a carrier board with full usb-c function, especially alt-dp ?

**Comment by swdee** [comment]
Personally I haven't used that, but see the Radxa CM5-IO carrier board [schematics page 18](https://dl.radxa.com/cm5/io_board_v2200/radxa_cm5_io_board_v2200_schematic.pdf).

Another reference for a carrier board is the [Retro-lite](https://github.com/StonedEdge/Retro-Lite-CM5)
