### ISSUE TITLE
Unit-C/J1 pins swapped

### ISSUE THREAD

**Issue by tyllurius** [swdee/radxa-cm5-kicad#2]
Hi, on the footprint the pins of J1/Port C are swapped, pin 1 is on the left side, whereas on Port A/B pin 1 is on the right side.

**Comment by swdee** [comment]
I have checked again and see what you mean, but this is how it is based on the Radxa IO carrier board reference.

<img width="810" alt="cm5-kicad-footprint" src="https://github.com/user-attachments/assets/8fb5a995-c0d0-48f7-a7e5-c97e8485c6f5" />

If you want to check for yourself, see [PCB layout files here](https://github.com/radxa/radxa-cm-projects/tree/main/cm5/radxa-cm5-io-board).

**Comment by tyllurius** [comment]
Thanks for the image and for clarification, I was too lazy to install Orcad Viewer. None of the other CM5 documents point out the location of pin 1 :/ . Did you check if any of the functions on J1 is working with this layout?

**Comment by swdee** [comment]
The Mechanical Test Board checks the pinout/orientation of the footprint connectors by picking unique GND pins and these have been verified when mated with the CM5 module by doing a simple continuity test.  On J1 this is Pins 201 and 213, so yes the J1 pinout is confirmed working as an incorrect layout would mean the continuity test would have failed.
